version: 2
updates:
  - package-ecosystem: "gradle"
    directories:
      - "/"
      - "/aidl"
      - "/api"
      - "/demo"
      - "/demo-hidden-api-stub"
      - "/provider"
      - "/rish"
      - "/server-shared"
      - "/shared"
    schedule:
      interval: "weekly"
    groups:
      gradle:
        patterns:
          - "*"
